apiVersion: v1
kind: Service
metadata:
  name: {{ include "obs-api-layer.fullname" . }}
  labels:
    {{- include "obs-api-layer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "obs-api-layer.selectorLabels" . | nindent 4 }}
