# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-lint-and-test-helm-charts

on:
  push:
    paths:
      - 'charts/**'
    branches:
      - main
  pull_request:
    paths:
      - 'charts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  helm-chart-lint-test:
    name: Helm charts lint & test
    uses: ./.github/workflows/reusable-helm-lint-test.yaml
    with:
      chart-path: charts
      dependencies: ""
