# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: mce-testing

on:
  pull_request:
    paths:
      - 'metrics_computation_engine/**'
      - '.github/workflows/mce_tests.yaml'

jobs:
  mce-run-tests:
    name: Run pytest on the MCE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # legit:ignore

      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          py-install: false
          poetry-install: false
          uv-install: true
      - name: Build package
        run: |
          pushd metrics_computation_engine
          uv build
      - name: Create virtual environment and install dependencies
        run: |
          pushd metrics_computation_engine
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[test]"
          uv pip install -e plugins/mce_metrics_plugin/
          uv pip install -e plugins/adapters/deepeval_adapter/
          uv pip install -e plugins/adapters/ragas_adapter/
          uv pip install -e plugins/adapters/opik_adapter/
      - name: Run tests
        run: |
          pushd metrics_computation_engine
          uv run pytest -m "not e2e"
